### ISSUE TITLE
[MQTT V5] Clean Start and Session Expiry Interval 

### ISSUE THREAD

**Issue by juanjoSanz** [emqx/nanomq#1009]
MQTT v5 standard defines two properties for handling sessions: Clean Start and Session Expiry Interval.

1. The first one is documented on the doc site: https://nanomq.io/docs/en/latest/config-description/v014.html#parameter-description

`bridge.mqtt.nodes[0].connector.clean_start | Boolean | Clean session.
`

2. Documentation is missing for the second one, "Session Expiry Interval"

Could you please guide us how to set this property? Also It would be nice to have it documented.

Thanks

**Comment by JaylinYu** [comment]
Thanks for your detailed issue.

I apologize that Session Expiry Interval is not exposed in bridging settings. And it should be configurable, as along with other MQTT V5 connect properties. I will make this available in the next version 0.15.5, perhaps next week.

**Comment by juanjoSanz** [comment]
Thanks for the support,

To enable never expire session would you accept "session_expiry_interval = 0xFFFFFFFF" ?

**Comment by alvin1221** [comment]
Only decimal allowed : 
`session_expiry_interval = 4294967295`

**Comment by JaylinYu** [comment]
If this work for you, plz close the issue. thanks
