### ISSUE TITLE
Incompatible on Windows 11

### ISSUE THREAD

**Issue by xiaobingcaicai** [emqx/nanomq#1057]
**Describe the bug**
windows平台，连接服务后直接执行消息发布，执行多次发布操作后服务进程闪退

**Expected behavior**
服务进程正常运行

**Actual Behavior**
服务进程异常退出

** Environment Details **
 - NanoMQ v0.15.2
 - windows 11

**Additional context**
1. 启动服务
2. 向一个topic发布消息
3. 订阅该topic
4. 继续向topic发布消息x2

**Comment by JaylinYu** [comment]
多谢报告问题，兼容问题已经修复
