### ISSUE TITLE
错误的描述信息

### ISSUE THREAD

**Issue by xiaobingcaicai** [emqx/nanomq#1061]
File: [/docs/zh_CN/README.md](https://nanomq.io/docs/zh/latest/)

···[NanoMQ (opens new window)](https://nanomq.io/zh)NanoMQ 致力于解决这些问题···

**Comment by JaylinYu** [comment]
Honestly, I don't know what you mean....
能描述一下什么错误么？ Readme 和 官网内容就是不一样的

**Comment by xiaobingcaicai** [comment]
![image](https://user-images.githubusercontent.com/4952024/219598223-26617180-fac3-435f-9d39-99cc4b265139.png)
文字描述部分。

**Comment by xiaobingcaicai** [comment]
> Honestly, I don't know what you mean.... 能描述一下什么错误么？是指多了一个NanoMQ的链接？

![image](https://user-images.githubusercontent.com/4952024/219598373-e60dfb6f-66d7-4847-9a23-65b957adcc0c.png)

**Comment by JaylinYu** [comment]
roger！

**Comment by JaylinYu** [comment]
已更新文档说明，下次此类问题欢迎直接提交文档修改PR！
