### ISSUE TITLE
The broker does not seem to handle SIGTERM properly.

### ISSUE THREAD

**Issue by mfechtner** [emqx/nanomq#1062]
**Describe the bug**

**Expected behavior**

**Actual Behavior**
Describe what occurred.

**To Reproduce**
If possible include actual reproduction test code here.
Minimal C test cases are perferred.

** Environment Details **
 - NanoMQ version
 - Operating system and version
 - Compiler and language used
 - testing scenario

**Client SDK**
If possible include the mqtt sdk you used to connect to nanomq
Minimal C test cases are perferred.

**Additional context**

**Comment by JaylinYu** [comment]
Understood! What do you suggest then?
