### ISSUE TITLE
Enabling DDS proxy conflicts with other build options

### ISSUE THREAD

**Issue by sikmir** [emqx/nanomq#1070]
**Describe the bug**
Build nanomq with:
 - `-DBUILD_DDS_PROXY=ON -DENABLE_RULE_ENGINE=ON ...`
 - `-DBUILD_DDS_PROXY=ON -DBUILD_ZMQ_GATEWAY=ON ...`

**Expected behavior**
Successful build. 

**Actual Behavior**
Build failed with:
```sh
       > duplicate symbol '_fatal' in:
       >     nanomq_cli/CMakeFiles/nanomq_cli.dir/dds2mqtt/mqtt_client.c.o
       >     nanomq_cli/CMakeFiles/nanomq_cli.dir/rule_ctrl.c.o
```
or
```sh
       > duplicate symbol '_client_publish' in:
       >     nanomq_cli/CMakeFiles/nanomq_cli.dir/dds2mqtt/mqtt_client.c.o
       >     nanomq_cli/CMakeFiles/nanomq_cli.dir/zmq_gateway.c.o
```

**Environment Details**
 - NanoMQ 0.5.15
 - NixOS

**Comment by JaylinYu** [comment]
Could you plz try the updated master branch on NixOS to see if this has been fixed?

**Comment by sikmir** [comment]
> Could you plz try the updated master branch on NixOS to see if this has been fixed?

Yes, build is OK now. Thanks! Already merged into nixpkgs.
