### ISSUE TITLE
Nanomq container stop after take message

### ISSUE THREAD

**Issue by esefberfu** [emqx/nanomq#1077]
**Describe the bug**
I am using nanomq briding between my emqx server and my app. My app publish messages successfully over nanomq but Other app publish message to my app(subscriptions over nanomq), message cames to my app and nanomq container closing simultaneously. I try different topic and different message data but result is same. I share logs and nanomq.conf file below.

[nanomq-logs.txt](https://github.com/emqx/nanomq/files/10809303/nanomq-logs.txt)
[nanomq.c
![photo_2023-02-23_03-22-28](https://user-images.githubusercontent.com/33575745/220794300-eb5600ef-ec85-4de8-853c-c7fe1195905f.jpg)
onf.txt](https://github.com/emqx/nanomq/files/10809304/nanomq.conf.txt)

**Comment by JaylinYu** [comment]
There is an identified bridging bug in 0.15.2, you probably run into it. Could you plz update your nanomq docker to latest version to check if this happens again?

**Comment by esefberfu** [comment]
> There is an identified bridging bug in 0.15.2, you probably run into it. Could you plz update your nanomq docker to latest version (0.15.5) to check if this happens again?

I have installed 0.15 version. I update to 0.15.5 and problem fixed. Thanks
