### ISSUE TITLE
Dynamic bridging subscription

### ISSUE THREAD

**Issue by esefberfu** [emqx/nanomq#1078]
Is there any api to change bridging subscriptions dynamically ?

**Comment by takaomag** [comment]
+1

In my understanding, both NanoMQ bridge and Mosquitto bridge act statically. That is, subscription topic paths MUST be known in advance.

But in some scenarios, edge clients under an MQTT broker want to subscribe topics which paths are dynamically determined.
For example,
- Isolated Response topic.
- One or more edge clients want to share a topic, in response to some events.

Dynamic topic subscription is one of the most important advantages over the similar protocols (like AMQP).
It would be nice if a remote subscription starts in response to a subscription request from an edge client.
I am not sure the difficulty. Just idea.

**Comment by JaylinYu** [comment]
This feature is already ready for using. Docs will be online in 0.19

**Comment by wanghaEMQ** [comment]
Tips: Via HTTP APIs (aka RestAPI) :)
