### ISSUE TITLE
Last Will message when remote bridge connection is broken

### ISSUE THREAD

**Issue by takaomag** [emqx/nanomq#1091]
About NanoMQ bridge mode.

Currently, NanoMQ bridge mode does not support Last Will message when remote connection is broken.
It would be nice if Last Will related parameters can be configured for remote bridge connection.

- will topic
- will payload
  May be plain text or json.
- will qos
- will retain
- will delay interval
- will message expiry interval
- others?
  payload format indicator, content type, user property, response topic, correlation data

It seems bridge connection code is [bridge.c](https://github.com/emqx/nanomq/blob/master/nanomq/bridge.c
). But I'm not familiar with C. Sorry..

Thanks.

**Comment by JaylinYu** [comment]
Will implement this in next version (0.16.6)

**Comment by takaomag** [comment]
Thank you so much !
