### ISSUE TITLE
NanoMQ bridge can not forward messages from remote broker (proto version 5)

### ISSUE THREAD

**Issue by takaomag** [emqx/nanomq#1093]
Hi,

In case of `connector.proto_ver=5`, NanoMQ bridge mode can not forward messages from a remote broker, and shows `decode message failed`.

On the other hand, in case of `connector.proto_ver=4`, no problem.

NanoMQ bridge does not support MQTT ver5 ?

## Environment
- NanoMQ version: 0.16.0
- Linux distribution: Archlinux ~~arm~~ x86_64 (all packages are latest)

## To Reproduce
1. Build NanoMQ
```
sudo rm -rf /var/tmp/nanomq-build && \
mkdir /var/tmp/nanomq-build && \
cd /var/tmp/nanomq-build && \
git clone https://github.com/emqx/nanomq.git -b 0.16.0 && \
cd nanomq && \
git submodule update --init --recursive && \
cmake -B build -G Ninja 
-DCMAKE_INSTALL_PREFIX="" \
-DENABLE_JWT=ON \
-DNNG_ENABLE_QUIC=ON && \
DESTDIR=/opt/local/nanomq sudo -E ninja -C build install
```

2. Edit `nanomq.conf`
Just change only the following settings.
```
bridge.mqtt.nodes[0].connector.server = "mqtt-tcp://broker.emqx.io:1883"
bridge.mqtt.nodes[0].connector.proto_ver = 5
bridge.mqtt.nodes[0].congestion_control = "bbr"
bridge.mqtt.nodes[0].forwards = ["fwd-topic/1/#", "fwd-topic/2/#"]
bridge.mqtt.nodes[0].subscription = [
  {
    topic = "sub-topic/1/#"
    qos = 1
  }
  {
    topic = "sub-topic/2/#"
    qos = 2
  }
]
```

3. Start NanoMQ
```
/opt/local/nanomq/bin/nanomq start --conf the_edited_config_file
```

4. Client X connects the NanoMQ, and subscribes `sub-topic/2/xxx` with OoS=2.

4. Client Y connects `broker.emqx.io:1883`, and publishes a message to `sub-topic/2/xxx`.

6. Result
No messages arrives on Client X subscription `sub-topic/2/xxx`.
NanoMQ console log shows the following line.
```
2023-03-09 17:43:24 [210596] WARN  /var/tmp/nanomq-build/nanomq/nanomq/pub_handler.c:1082 handle_pub: decode message failed.
```

Thanks.

**Comment by takaomag** [comment]
I made a mistake.
I tested it on Archlinux x86_64, not arm.

> - Linux distribution: Archlinux arm (all packages are latest)

-->
- Linux distribution: Archlinux ~~arm~~ x86_64 (all packages are latest)

**Comment by JaylinYu** [comment]
Hello takaomag san, We faile to reproduce your bug, but instead we found another issue from your scenario! Thank you for submitting the issue!

Could you plz provide us with the log file of nanomq in trace/debug level? So that we can keep on investigating on other clues.

Thanks!

**Comment by takaomag** [comment]
Hi @JaylinYu,

Thank you for your investigation.
I found the reason why you can not reproduce the problem. The my procedure listed above was incomplete, sorry.
I rewrite the procedure to reproduce it again.

## The procedure to reproduce
1. Build NanoMQ
```
sudo rm -rf /opt/local/nanomq && \
sudo rm -rf /var/tmp/nanomq-build && \
mkdir /var/tmp/nanomq-build && \
cd /var/tmp/nanomq-build && \
git clone https://github.com/emqx/nanomq.git -b 0.16.0 && \
cd nanomq && \
git submodule update --init --recursive && \
cmake -B build -G Ninja \
-DCMAKE_INSTALL_PREFIX="" \
-DENABLE_JWT=ON \
-DNNG_ENABLE_QUIC=ON && \
DESTDIR=/opt/local/nanomq sudo -E ninja -C build install
```

2. Prepare 2 config files
2.1 `from_example.conf` which is derived from `etc/nanomq_example.conf`
2.2 `from_default.conf` which is derived from `etc/nanomq.conf`

Both config files are contained in the attached zip file. Basically, Just changed only the following settings.
```
log.level = debug
bridge.mqtt.nodes[0].enable = true
bridge.mqtt.nodes[0].connector.server = "mqtt-tcp://broker.emqx.io:1883"
bridge.mqtt.nodes[0].connector.proto_ver = 5
bridge.mqtt.nodes[0].congestion_control = "bbr"
bridge.mqtt.nodes[0].forwards = ["fwd-topic/1/#", "fwd-topic/2/#"]
bridge.mqtt.nodes[0].subscription = [
  {
    topic = "sub-topic/1/#"
    qos = 1
  }
  {
    topic = "sub-topic/2/#"
    qos = 2
  }
]
```

3. Start NanoMQ with `from_example.conf` or `from_default.conf`.
```
LD_LIBRARY_PATH=/opt/local/nanomq/lib /opt/local/nanomq/bin/nanomq start \
--conf from_example.conf
```
or
```
LD_LIBRARY_PATH=/opt/local/nanomq/lib /opt/local/nanomq/bin/nanomq start \
--conf from_default.conf
```

4. Subscribes `sub-topic/2/xxx` with OoS=2 on the local NanoMQ.
```
mosquitto_sub -h 127.0.0.1 -p 1883 -V mqttv5 \
-u "client-x" \
-i "client-x" \
-c \
-t "sub-topic/2/xxx" \
-k 28 \
-q 2 \
-d
```

5. Publishes a message to `sub-topic/2/xxx` on `broker.emqx.io:1883`
```
mosquitto_pub -h broker.emqx.io -p 1883 -V mqttv5 \
-u "client-y" \
-i "client-y" \
-t sub-topic/2/xxx \
-q 2 \
-d \
-m "test"
```

6. Result
- In case of `from_default.conf`
No problem. The subscriber receives the published message.

- In case of `from_example.conf`
The subscriber can not receive the published message. NanoMQ show a log,
```
WARN  /var/tmp/nanomq-build/nanomq/nanomq/pub_handler.c:1082 handle_pub: decode message failed.
```

## Debug log files
- `from_default.log`
Successful log file generated by `from_default.conf`

- `from_example.log`
Erroneous log file generated by `from_example.conf`. You can find the line `decode message failed.`

[bridge-conf-log.zip](https://github.com/emqx/nanomq/files/10950398/bridge-conf-log.zip)

**Comment by takaomag** [comment]
Above log files are `Debug` level.

This attached file is a `Trace` level log file generated by `from_example.conf`, when bridging failed.
[from_example_trace.zip](https://github.com/emqx/nanomq/files/10950585/from_example_trace.zip)

It seems that the subscriber receives 2 messages, one of which seems to be a retained message (I did not publish it when testing).
Anyway, those 2 message resulted in `decode message failed`, and bridging failed.

**Comment by JaylinYu** [comment]
HI takaomag san,

Thanks for your detailed log. The bug has been identified. 
I mistaken all subid of publish msg as illegal. Publish msg from client should not contain subscription id, but publish msg from broker could.

**Comment by takaomag** [comment]
Thanks,  JaylinYu!

I will test it when it is merged.

**Comment by takaomag** [comment]
It works well!
Thank you jaylinYu1
