### ISSUE TITLE
It is easy to make mistakes when setting subscriptions counter.

### ISSUE THREAD

**Issue by wanghaEMQ** [emqx/nanomq#1128]
**Is your feature request related to a problem? Please describe.**
It is easy to make mistakes when setting subscriptions counter.

**Describe the solution you'd like**
No subscriptions counter should be inputed.

**Comment by alvin1221** [comment]
It's unfriendly to change common APIs, I'll specify what the field does in demos.

**Comment by wanghaEMQ** [comment]
Fine
