### ISSUE TITLE
nanomq_cli pub does not exit after publishing a message

### ISSUE THREAD

**Issue by decadenza** [emqx/nanomq#1148]
**Describe the bug**
Executing the following command via shell on Linux Debian:
`nanomq_cli pub --url "mqtt-tcp://127.0.0.1:1883" -t my/topic -m 'mymessage'`

The result is:
```
> connect_cb: mqtt-tcp://127.0.0.1:1883 connect result: 0
>
```

**Expected behavior**
The command should publish and **exit**.
For reference, the `mosquitto_pub` command does exit at the end as expected.

**Actual Behavior**
The terminal hangs there.

**To Reproduce**
Just run the command above.

**Environment Details**
 - NanoMQ version 0.15.0
 - Debian Bookworm

**Comment by JaylinYu** [comment]
This is a known issue or feature (^_^)
will fix this

**Comment by JaylinYu** [comment]
Have made it as your wish

**Comment by andersonvom** [comment]
Hi @JaylinYu, I'm still seeing a similar behavior on version [`0.22.8`][1] (tested with the image from docker hub):

```shell
$ cat /etc/alpine-release
3.16.9

$ nanomq --version

Usage: nanomq { start | stop | restart | reload } [--help]

NanoMQ Messaging Engine for Edge Computing & Messaging bus v0.22.8-10
Copyright 2023 EMQ Edge Computing Team

$ mqtt nanomq_cli pub -t "test/some-topic" -m "test"
connect_cb: mqtt-tcp://127.0.0.1:1883 connect result: 0
disconnected reason : 0
# command does not return
```

I've also tried using `--limit 1` and `--stdin-line`, but they all yield the same result.

[1]: https://hub.docker.com/layers/emqx/nanomq/0.22.8/images/sha256-0dab3f10c870719ee7e219fbe921a82d28d0ac057908fc4556450d4db7ff5086?context=explore
