### ISSUE TITLE
NanoMQ process crashes when reloading configuration file with 'munmap_chunk(): invalid pointer' error

### ISSUE THREAD

**Issue by Just1ceP4rtn3r** [emqx/nanomq#1171]
**Describe the bug**
When using `nanomq start --conf /etc/nanomq.conf` followed by `nanomq reload` to reload the configuration file, the NanoMQ process crashes and reports an error message: 
```
munmap_chunk(): invalid pointer
Aborted (core dumped)
```
**Expected behavior**
I expected the NanoMQ process to reload the configuration file without crashing.

**Actual Behavior**
The NanoMQ process crashes and reports an error message: `munmap_chunk(): invalid pointer`.

**To Reproduce**
1. Run `nanomq start --conf /etc/nanomq.conf`
2. Run `nanomq reload`

**Environment Details**
- NanoMQ version: 0.17.5
- Operating system and version: `Linux ccdecc0ea4a2 5.13.0-52-generic #59-Ubuntu SMP Wed Jun 15 20:17:13 UTC 2022 x86_64 GNU/Linux`
- Compiler and language used: N/A
- Testing scenario: N/A

**Client SDK**
N/A

**Additional context**
N/A

**Comment by JaylinYu** [comment]
Fixed, plz verify and reopen issue if you found any new problems
