### ISSUE TITLE
Unable to use Nano MQ Gateway tool - Request for Source code for Windows OS to build NanoMQ Gateway Tool

### ISSUE THREAD

**Issue by anandbwfrd** [emqx/nanomq#1183]
### Discussed in https://github.com/emqx/nanomq/discussions/1182

<div type='discussions-op-text'>

<sup>Originally posted by **anandbwfrd** April 18, 2023</sup>
How can I subscribe to a topic from an external MQTT Broker and publish the content to a new topic on local MQTT Broker using the nanomq_cli tool on Windows OS?  I think it requires the usage of the NanoMQGateway tool which isn't built by default.  I need access to the Windows Source code to be able to build it using CMAKE and Ninja - Screenshot attached below.  Please confirm if the NanoMQGateway tool is supported on the Windows Platform.
![Screenshot 2023-04-18 201451](https://user-images.githubusercontent.com/112025627/232942152-be2bc2c0-b72c-4a06-87d5-a3de4474ec3e.png)
</div>

**Comment by JaylinYu** [comment]
Seems like you have figured it out on Discord
Yes, MQTT Bridge is where you should go

THanks

**Comment by JaylinYu** [comment]
ZMQ gateway is a tool for proxying msg from ZeroMQ to MQTT
