### ISSUE TITLE
[Security]: UAF of retain msg in sub_Ctx_handle

### ISSUE THREAD

**Issue by songxpu** [emqx/nanomq#1217]
**Describe the bug**

Hi! 
We have discovered a UAF vulnerability in our latest branch, here are the details.

The following information is provided to facilitate reproduction.

**To Reproduce**
If possible include actual reproduction test code here.
Minimal C test cases are perferred.

**Environment Details**

 - NanoMQ version #5a8f908c09f23c54d8d82ade607d7cffda80358e
 - NanoNNG #2fc2c28d74ad2bc31c73fdf067d0e49c0c163485

![image](https://user-images.githubusercontent.com/44093631/235565101-a4f2571c-07a7-4357-8acb-73106107367e.png)

[UAF_sub_handler_c_316.zip](https://github.com/emqx/nanomq/files/11369196/UAF_sub_handler_c_316.zip)

**Comment by JaylinYu** [comment]
Data racing of retain msg still exist in Sub logic
