### ISSUE TITLE
http server open jwt auth fail

### ISSUE THREAD

**Issue by zmkn** [emqx/nanomq#1221]
**Describe the bug**
http_server enable jwt, request response error, {"code":103}

**Actual Behavior**
console print “ERROR /home/runner/work/nanomq/nanomq/nanomq/rest_api.c:627 jwt_authorize: decode jwt token failed: return 0, result: 1”

**To Reproduce**
jwt payload: {
  "exp": 1683292928,
  "username": "admin",
  "password": "public"
}

** Environment Details **
 - NanoMQ version docker image 0.17.9-full
 - debian 11.5

**Additional context**
postman jwt config screenshot:

<img width="438" alt="1683222649904" src="https://user-images.githubusercontent.com/1784566/236287894-d97b0ced-31bc-4e19-be05-556372b3da83.png">

docker log screenshot:

<img width="1069" alt="1683222824201" src="https://user-images.githubusercontent.com/1784566/236288238-4466f636-d25f-4736-855f-6ce57dc8337d.png">

**Comment by alvin1221** [comment]
We are preparing the `JWT` guidance document, you need to follow the `token` generation rules and configuration method .
