### ISSUE TITLE
rule engine is not supported in full-tag docker images

### ISSUE THREAD

**Issue by ChanZany** [emqx/nanomq#1325]
**Describe the bug**
rule engine is not supported in full-tag docker images
 
**To Reproduce**
It looks like the rules engine was not enabled when the docker image was compiled

** Environment Details **
 - NanoMQ version: 0.18.2
 - Operating system and version: ubuntu20.04, docker 19.03.8

**Comment by Rory-Z** [comment]
> It looks like the rules engine was not enabled when the docker image was compiled

@JaylinYu How to enable rules engine when code compile ?

**Comment by lee-emqx** [comment]
> **Describe the bug** rule engine is not supported in full-tag docker images
> 
> **To Reproduce** It looks like the rules engine was not enabled when the docker image was compiled
> 
> ** Environment Details **
> 
> * NanoMQ version: 0.18.2
> * Operating system and version: ubuntu20.04, docker 19.03.8

Since 0.19.0, rule engine is supported in full-tag docker images.

**Comment by lee-emqx** [comment]
This issue has been resoloved. If you have any further questions, you can reopen it.
