### ISSUE TITLE
There is an error in the auth configuration description

### ISSUE THREAD

**Issue by whyitdo** [emqx/nanomq#1400]
File: [/docs/zh_CN/access-control/http.md](https://nanomq.io/docs/zh/latest/access-control/http.html)
![image](https://github.com/emqx/nanomq/assets/58539745/dcf8352e-68ae-4e6d-b316-ec37e9be09dd)

password value is %P not %p
![image](https://github.com/emqx/nanomq/assets/58539745/da15e104-e3aa-4ce7-a132-39eeb92fd0f8)

**Comment by JaylinYu** [comment]
Thanks for your reminder. I can fix this by my own, But... since you share the credit, could you fix it via a PR?
