### ISSUE TITLE
EMQX WebSocket client failed to connect to nanomq WebSocket port

### ISSUE THREAD

**Issue by RanMaoyi** [emqx/nanomq#1420]
**Describe the bug**
EMQX WebSocket client failed to connect to nanomq WebSocket port

**Expected behavior**
EMQX WebSocket client connect to nanomq WebSocket port successfully

**Actual Behavior**
EMQX WebSocket client failed to connect to nanomq WebSocket port.
![image](https://github.com/emqx/nanomq/assets/16575896/392f732f-944c-497b-8192-382fa06a185b)
![image](https://github.com/emqx/nanomq/assets/16575896/aa0682ee-8be4-458f-9c05-4dc233568834)

**To Reproduce**
Use emqx WebSocket client to connect to nanomq

** Environment Details **
 - NanoMQ version: master
 - Operating system and version: ubuntu 22.04
 - Compiler and language used
 - testing scenario

**Client SDK**
If possible include the mqtt sdk you used to connect to nanomq
Minimal C test cases are perferred.

**Additional context**

**Comment by JaylinYu** [comment]
might be same problem as https://github.com/emqx/nanomq/issues/1210

**Comment by JaylinYu** [comment]
not an issue
