### ISSUE TITLE
$SYS event msgs (online/offline) are incomplete

### ISSUE THREAD

**Issue by AetheWu** [emqx/nanomq#1445]
**Describe the bug**
$SYS event online/offline msgs are incomplete; the message is truncated after reaching 255 bytes

**Expected behavior**
complete $SYS event msg

**Actual Behavior**
$SYS event online/offline message is truncated after reaching 255 bytes

**To Reproduce**
If possible include actual reproduction test code here.
Minimal C test cases are perferred.

** Environment Details **
 - NanoMQ version 0.19.5
 - Operating system and version linux-arm7
 - Compiler and language used 
 - testing scenario

**Comment by AetheWu** [comment]
we can't receive offline event message when the client broken (tcp connection break );

**Comment by JaylinYu** [comment]
😆 Apologize that NanoMQ limit the online/offline msg to 255 bytes for saving memory. How long do you suggest then?

And, as for your missing disconnect may, is that same issue due to msg length? Only session close Gonna trigger the offline msg.

**Comment by AetheWu** [comment]
How about 512 bytes

**Comment by AetheWu** [comment]
> we also can't receive offline event message when the client broken (tcp connection break );

When the mqtt client set clean_session to false and disconnect to nanomq, the disconnected event do not publish

**Comment by JaylinYu** [comment]
> > we also can't receive offline event message when the client broken (tcp connection break );
> 
> 
> 
> When the mqtt client set clean_session to false and disconnect from nanomq, the disconnected event do not publish

Yup, this is expected, and concluded as a feature. 😮

From broker' view, in this case the client is still connected, mqtt protocol allows client restore previous session. 

You can set "session expiry interval" to control How long does Broker keep this session.

**Comment by JaylinYu** [comment]
> How about 512 bytes

Easy thing. 
How about i point the code for you, and you made a pr?
Or you prefer i do this for u?

**Comment by AetheWu** [comment]
> > > we also can't receive offline event message when the client broken (tcp connection break );
> > 
> > 
> > When the mqtt client set clean_session to false and disconnect from nanomq, the disconnected event do not publish
> 
> Yup, this is expected, and concluded as a feature. 😮
> 
> From broker' view, in this case the client is still connected, mqtt protocol allows client restore previous session.
> 
> You can set "session expiry interval" to control How long does Broker keep this session.

How to set "session expiry interval"? I didn’t find the relevant parameters in the configuration example.

**Comment by AetheWu** [comment]
> > How about 512 bytes
> 
> Easy thing. How about i point the code for you, and you made a pr? Or you prefer i do this for u?

Please make a pr for me, thanks 🥳
