### ISSUE TITLE
How to set "session expiry interval"?

### ISSUE THREAD

**Issue by AetheWu** [emqx/nanomq#1461]
**Describe the bug**
Does nanomq support the session expiry interval set ?  how to set it ?

**Expected behavior**

**Actual Behavior**
Describe what occurred.

**To Reproduce**
If possible include actual reproduction test code here.
Minimal C test cases are perferred.

** Environment Details **
 - NanoMQ version 0.19.5
 - Operating system and version
 - Compiler and language used
 - testing scenario

**Client SDK**
If possible include the mqtt sdk you used to connect to nanomq
Minimal C test cases are perferred.

**Additional context**

**Comment by wanghaEMQ** [comment]
@AetheWu 

Hi AetheWu,
`session expiry interval` is a property for the MQTT client.
So there is no place in NanoMQ to set this property.
