### ISSUE TITLE
topic reflection not working as expected in aws bridge.

### ISSUE THREAD

**Issue by OdyWayne** [emqx/nanomq#1477]
**Describe the bug**
aws bridge topic reflection is not working as expected, subscription still works in the previous way.

**Expected behavior**
aws bridge topic reflection works as expected.

**Actual Behavior**
aws bridge will forward msg from remote_topic to itself instead of local_topic

** Environment Details **
 - NanoMQ version latest main branch
 - Operating system and version Ubuntu 22.04

**Comment by OdyWayne** [comment]
I think I have just fixed it, gonna be a PR tmr.

**Comment by OdyWayne** [comment]
I think I have just fixed it, gonna be a PR tmr.

**Comment by OdyWayne** [comment]
fixed --> https://github.com/emqx/nanomq/pull/1479

**Comment by JaylinYu** [comment]
cool
