### ISSUE TITLE
The "resend_interval" parameter is invalid

### ISSUE THREAD

**Issue by ivanbearcat** [emqx/nanomq#1483]
The "resend_interval" parameter is invalid.

No matter how I set the resend interval to always be 10 seconds.

NanoMQ version:  nanomq-0.20.0-linux-x86_64-sqlite
OS: Centos 8.5

Here is my nanomq.conf

        mqtt {
            property_size = 32
            max_packet_size = 10KB
            max_mqueue_len = 2048
            retry_interval = 20s
            keepalive_multiplier = 1.25
            
            # Three of below, unsupported now
            max_inflight_window = 2048
            max_awaiting_rel = 10s
            await_rel_timeout = 10s
        }
        
        sqlite {
            disk_cache_size = 102400  # 最大缓存消息数
            mounted_file_path="/work/nanomq_cache" # 数据库文件存储路径
            flush_mem_threshold = 1 # 内存缓存消息数阈值
            resend_interval = 1000    # 故障恢复后的重发时间间隔 (ms)
        }
        
        rules.sqlite = {
          path = "/work/nanomq_cache/sqlite_rule.db"          # SQLite 数据库文件路径
          rules = [
            {
              sql = "SELECT * FROM \"DDD\""  # 规则 SQL
              table = "DDD"                  # 规则的表名
            }
          ]
        }
        
        listeners.tcp {
            bind = "0.0.0.0:1883"
        }
        
        
        listeners.ws {
            bind = "0.0.0.0:8083/mqtt"
        }
        
        http_server {
            port = 18081
            limit_conn = 2
            username = admin
            password = public
            auth_type = basic
            jwt {
                public.keyfile = "/etc/certs/jwt/jwtRS256.key.pub"
            }
        }
        
        log {
            to = [file, console]
            level = info
            dir = "/tmp"
            file = "nanomq.log"
            rotation {
                size = 10MB
                count = 5
            }
        }
        
        auth {
            allow_anonymous = true
            no_match = allow
            deny_action = ignore
            
            cache = {
                max_size = 32
                ttl = 1m
            }
           
        }
        
        bridges.mqtt.emqx1 = {
          server = "mqtt-tcp://192.168.1.223:1883"    # MQTT 服务器地址
          proto_ver = 4                           # MQTT 协议版本
          clientid = "bridge_client"              # 桥接的客户端 ID
          keepalive = "20s"                       # 桥接的保活间隔时间（s）
          clean_start = false                     # 清除会话
          username = "username"                   # 桥接用户名
          password = "passwd"                     # 桥接密码
        
          forwards = [
		        {
			        remote_topic = "DDD"
			        local_topic = "DDD"
			        qos = 1
		        }
	        ]
        
          max_parallel_processes = 2              # 最大并行进程数
          max_send_queue_len = 32								  # 消息发送队列的最大长度
          max_recv_queue_len = 128								# 消息接收队列的最大长度
        }
        
        bridges.mqtt.cache {
            disk_cache_size = 102400   # 缓存的最大消息限制
            mounted_file_path="/work/nanomq_cache"  # 挂载的文件路径
            flush_mem_threshold = 1  # 刷新消息到闪存的阈值
            resend_interval = 1000     # 故障恢复后消息的重发间隔
        }

**Comment by JaylinYu** [comment]
fixed in #1484 
Only following takes effect
```
bridges.mqtt.cache {
        disk_cache_size = 102400   # 缓存的最大消息限制
        mounted_file_path="/work/nanomq_cache"  # 挂载的文件路径
        flush_mem_threshold = 1  # 刷新消息到闪存的阈值
        resend_interval = 1000     # 故障恢复后消息的重发间隔
    }
```
