### ISSUE TITLE
forwards configuration incorrect since change in #1174

### ISSUE THREAD

**Issue by hawko2600** [emqx/nanomq#1486]
File: [/docs/en_US/config-description/bridges.md](https://nanomq.io/docs/en/latest/config-description/bridges.html)

Issue #1174 appears to have altered bridge configuration and the documentation hasn't kept pace.
My old config was along the lines of:
bridges.mqtt.foo {
  ...
  forwards = ["atopic"]
}

and this apparently must now be:
bridges.mqtt.foo {
  ...
  forwards = [
     local_topic = "atopic"
     remote_topic = "atopic"
  ]
}

**Comment by JaylinYu** [comment]
Somehow, docs isnt update with code, but I have pushed the new docs. Let me have a check

**Comment by brahste** [comment]
I was trialling NanoMQ and similarly noticed that the documentation for setting up MQTT bridging [here](https://nanomq.io/docs/en/latest/bridges/tcp-bridge.html#configure-mqtt-over-tcp-bridge) isn't up-to-date with the configuration file.

I would be glad to submit a PR to update the docs.

**Comment by JaylinYu** [comment]
That would be wonderful!

> I was trialling NanoMQ and similarly noticed that the documentation for setting up MQTT bridging [here](https://nanomq.io/docs/en/latest/bridges/tcp-bridge.html#configure-mqtt-over-tcp-bridge) isn't up-to-date with the configuration file.
> 
> I would be glad to submit a PR to update the docs.

**Comment by JaylinYu** [comment]
Gonna add a new configuring way to make it compatible with previous bridging behaviour.

**Comment by brahste** [comment]
My bad, hadn't checked this. Still seems that the documentation could use an update. Would you prefer we re-open this issue or make another one?

**Comment by JaylinYu** [comment]
> > Seems like we are a step ahead of you ~
> 
> Not entirely sure if I follow.
> 
> My bad for the delay here. Still seems that the documentation could use an update. Would you prefer we re-open this issue or make another one?

Your updates are welcome. Although we have made the fix, please point out the the defact in docs.

**Comment by brahste** [comment]
See PR #1509 for documentation updates

**Comment by JaylinYu** [comment]
Merged! Thank you for correcting mistakes!
