### ISSUE TITLE
[Docs]: Adding Dropdown Feature in Test Report Documentation

### ISSUE THREAD

**Issue by Smartmind12** [emqx/nanomq#1492]
**Is your feature request related to a problem? Please describe.**
I'm was annoyed to see all the lengthy ping status and scroll all the way down to reach the test summary when i was reading through the test report in NanoMQ Docs.

**Describe the solution you'd like**
I would like to propose the drop down feature in the docs so that it reduces the length of the page and improves readability of the documentation.

**Describe alternatives you've considered**
I believe adding drop down feature to hide and show the test pings status as per the user needs is the ideal solution for this.

**Additional context**
I would like to work on this issue as a part of Hacktoberfest contribution 

![Screenshot 2023-10-22 at 6 21 49 PM](https://github.com/emqx/nanomq/assets/91927689/2a80c182-579e-4410-8dc8-56b60c34bb6b)

**Comment by JaylinYu** [comment]
sure, will make it happen.

**Comment by Smartmind12** [comment]
> sure, will make it happen.

Can i work on it and make a PR??

**Comment by JaylinYu** [comment]
Here you go. I have labeled it as Hacktoberfest.
Thank you for the initiative!

**Comment by Smartmind12** [comment]
> Here you go. I have labeled it as Hacktoberfest. I had a plan to add the updated benchmarking report of 0.18, just don't have enough time....
> 
> Anyway Thank you for the initiative! @Smartmind12

Thanks I am going to make the PR rightaway!

**Comment by Smartmind12** [comment]
@JaylinYu I have done the needful! Kindly review the same!
