### ISSUE TITLE
Error in Docs File: /docs/zh_CN/bridges/quic-bridge.md

### ISSUE THREAD

**Issue by soMagics** [emqx/nanomq#1494]
File: [/docs/zh_CN/bridges/quic-bridge.md](https://nanomq.io/docs/zh/latest/bridges/quic-bridge.html)

![图片](https://github.com/emqx/nanomq/assets/64079865/dd1f2575-605e-4e16-86b6-d4696ad149b2)
此处应该一个`-`符号

**Comment by JaylinYu** [comment]
Thank you!
