### ISSUE TITLE
[Docs]: Adding Summary and Architecture diagram in TestReport Page

### ISSUE THREAD

**Issue by Smartmind12** [emqx/nanomq#1501]
**Is your feature request related to a problem? Please describe.**
When going through the test reports in English and Chinese, the Chinese version consist of a Summary in the end of the test report along with Nanomq Architecture diagram. However, the same is absent in the English version and and users would not have the insight on the same.

**Describe the solution you'd like**

Adding the Summary of the test report and architecture of Nanomq.

**Describe alternatives you've considered**

**Additional context**

EN Version:
![Screenshot 2023-10-24 at 7 57 36 PM](https://github.com/emqx/nanomq/assets/91927689/31acba6b-94b3-4ee0-93b6-0ccd56997e44)

ZH Version:
![Screenshot 2023-10-24 at 8 06 16 PM](https://github.com/emqx/nanomq/assets/91927689/d65e6241-5dfe-4501-8eee-6a4eb49893cf)

**Comment by Smartmind12** [comment]
I would like to work on this as a part of Hacktober contribution ??

**Comment by Smartmind12** [comment]
Hey @JaylinYu Kindly review this PR ...Thanks!

**Comment by JaylinYu** [comment]
Thank you @Smartmind12 
But I wouldn't label it as Hacktoberfest because no coding is involved. 

Still appreciate your efforts!
