### ISSUE TITLE
Windows cmake build error

### ISSUE THREAD

**Issue by zsr391912829** [emqx/nanomq#1518]
Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19044.
-- NanoMQ versions --
Configuring for NanoMQ version 0.20.6
-- Build NanoMQ with ACL support --
-- MODE [Release] --
CMake Error at CMakeLists.txt:322 (add_subdirectory):
  The source directory

    D:/Users/Administrator/Desktop/nanomq-master/git/nanomq/nng

**Comment by JaylinYu** [comment]
you need to sync nanonng  https://github.com/nanomq/NanoNNG as well.

**Comment by zsr391912829** [comment]
> you need to sync nanonng https://github.com/nanomq/NanoNNG as well.

Thank you , I download NNG git code to nngDir , it's ok.
