### ISSUE TITLE
Rest api put sqlite rule may cause crash

### ISSUE THREAD

**Issue by OdyWayne** [emqx/nanomq#1520]
**Describe the bug**
double free in rest api put sqlite rule to cause crash

**To Reproduce**
post a sqlite rule in advance, then use put to update the sqlite rule. nanomq will crash for double free.

** Environment Details **
 - NanoMQ version : nanomq master latest
 - Operating system and version : ubt 22.04

**Comment by OdyWayne** [comment]
fix --> https://github.com/emqx/nanomq/pull/1514

**Comment by JaylinYu** [comment]
NIce
