### ISSUE TITLE
Windows Run error : broker nng_listen: Permission denied

### ISSUE THREAD

**Issue by zsr391912829** [emqx/nanomq#1521]
I user VS2022 build code , build OK .
do this cmd ,  
D:\Users\Administrator\Desktop\nanoMq\nanomq\build\nanomq\Debug>nanomq.exe start --conf D:\myemq.conf

broker nng_listen: Permission denied

**Comment by JaylinYu** [comment]
The warning is clear, you didn't give nanomq enough authority on networking. It is a broker, that need to bind to a local port.

**Comment by zsr391912829** [comment]
![image](https://github.com/emqx/nanomq/assets/18156380/dfe8d3f5-725f-4ea8-8711-a3a1f363309c)

**Comment by zsr391912829** [comment]
> The warning is clear, you didn't give nanomq enough authority on networking. It is a broker, that need to bind to a local port.

我的防火墙 已经全部关闭了哦。  broker的本地绑定端口 1883 ， 用TCP工具测试 是可以绑定的。UWC也没有弹出阻止之类的窗口。

**Comment by JaylinYu** [comment]
也可能是你的运行窗口的权限，win 测试可以通过。
我并不负责为您检查你的环境问题
