### ISSUE TITLE
seg. fault / pthread_mutex_lock

### ISSUE THREAD

**Issue by Grabber** [emqx/nanomq#196]
commit f9ae56e0180d4fc6c5db323964fab52b52f29eac

```
./build/nanomq/nanomq broker start -tq_thread 8 -max_tq_thread 8 -parallel 1 -msq_len 32 -url tcp://127.0.0.1:1883
```

```
mosquitto_sub -h 127.0.0.1 -t 'banana'
```

```
time $(for i in {1..1000}; do mosquitto_pub --id "f1c21f64" -h 127.0.0.1 -t "banana" -m "x"; done)
```

```
panic: pthread_mutex_lock: Invalid argument
This message is indicative of a BUG.
Report this at https://github.com/nanomq/nanomq
1   nanomq                              0x0000000101f4136c nni_panic + 524
2   nanomq                              0x0000000101f55dba nni_pthread_mutex_lock + 58
3   nanomq                              0x0000000101f55d75 nni_plat_mtx_lock + 21
4   nanomq                              0x0000000101f4afc5 nni_mtx_lock + 21
5   nanomq                              0x0000000101f496e7 nni_task_dispatch + 71
6   nanomq                              0x0000000101f37a0b nni_aio_begin + 331
7   nanomq                              0x0000000101f69521 tcptran_pipe_recv + 33
8   nanomq                              0x0000000101f41519 nni_pipe_recv + 41
9   nanomq                              0x0000000101f587c5 nano_ctx_recv + 869
10  nanomq                              0x0000000101f44c16 nni_ctx_recv + 54
11  nanomq                              0x0000000101f33386 nng_ctx_recv + 310
12  nanomq                              0x0000000101f30ad3 server_cb + 8899
13  nanomq                              0x0000000101f493f0 nni_taskq_thread + 144
14  nanomq                              0x0000000101f4b2ff nni_thr_wrap + 191
15  nanomq                              0x0000000101f561f8 nni_plat_thr_main + 120
16  libsystem_pthread.dylib             0x00007fff203398fc _pthread_start + 224
17  libsystem_pthread.dylib             0x00007fff20335443 thread_start + 15
zsh: abort      ./build/nanomq/nanomq broker start -tq_thread 8 -max_tq_thread 8 -parallel 1
```

**Comment by Grabber** [comment]
Apparently it has something with **-parallel 1**

**Comment by Grabber** [comment]
Another observation: single paralelism seems to be a little bit faster than with paralell > 1:

```
(base) lvmc@Luizs-MacBook-Pro nanomq % ./build/nanomq/nanomq broker start -tq_thread 8 -max_tq_thread 8 -parallel 1 -msq_len 32 -url tcp://127.0.0.1:1883
```

```
mosquitto_pub --id "f1c21f64" -h 127.0.0.1 -t "banana" -m "x" --repeat 100000  0.24s user 1.62s system 99% cpu 1.871 total
```

```
(base) lvmc@Luizs-MacBook-Pro nanomq % ./build/nanomq/nanomq broker start -tq_thread 8 -max_tq_thread 8 -parallel 32 -msq_len 32 -url tcp://127.0.0.1:1883
```

```
mosquitto_pub --id "f1c21f64" -h 127.0.0.1 -t "banana" -m "x" --repeat 100000  0.33s user 1.91s system 99% cpu 2.259 total
```

**Comment by JaylinYu** [comment]
> Apparently it has something with **-parallel 1**

Hi there is a resource dead lock risk with parallel set to 1. Please set the parallelism > 1 unless you are using a single core system.

**Comment by JaylinYu** [comment]
> Another observation: single paralelism seems to be a little bit faster than with paralell > 1:
> 
> ```
> (base) lvmc@Luizs-MacBook-Pro nanomq % ./build/nanomq/nanomq broker start -tq_thread 8 -max_tq_thread 8 -parallel 1 -msq_len 32 -url tcp://127.0.0.1:1883
> ```
> 
> ```
> mosquitto_pub --id "f1c21f64" -h 127.0.0.1 -t "banana" -m "x" --repeat 100000  0.24s user 1.62s system 99% cpu 1.871 total
> ```
> 
> ```
> (base) lvmc@Luizs-MacBook-Pro nanomq % ./build/nanomq/nanomq broker start -tq_thread 8 -max_tq_thread 8 -parallel 32 -msq_len 32 -url tcp://127.0.0.1:1883
> ```
> 
> ```
> mosquitto_pub --id "f1c21f64" -h 127.0.0.1 -t "banana" -m "x" --repeat 100000  0.33s user 1.91s system 99% cpu 2.259 total
> ```

well since you are testing on Mac, so I suppose nanomq is using kqueue under the hood. And your scenario is with much connection up and down. So that nanomq really cannot benefit much from parallelism (with more context switch burden). 
However, there should be no significant performance difference between parallel set to 1/32, if you have run the test multiple times

**Comment by JaylinYu** [comment]
> commit [f9ae56e](https://github.com/nanomq/nanomq/commit/f9ae56e0180d4fc6c5db323964fab52b52f29eac)
> 
> ```
> ./build/nanomq/nanomq broker start -tq_thread 8 -max_tq_thread 8 -parallel 1 -msq_len 32 -url tcp://127.0.0.1:1883
> ```
> 
> ```
> mosquitto_sub -h 127.0.0.1 -t 'banana'
> ```
> 
> ```
> time $(for i in {1..1000}; do mosquitto_pub --id "f1c21f64" -h 127.0.0.1 -t "banana" -m "x"; done)
> ```
> 
> ```
> panic: pthread_mutex_lock: Invalid argument
> This message is indicative of a BUG.
> Report this at https://github.com/nanomq/nanomq
> 1   nanomq                              0x0000000101f4136c nni_panic + 524
> 2   nanomq                              0x0000000101f55dba nni_pthread_mutex_lock + 58
> 3   nanomq                              0x0000000101f55d75 nni_plat_mtx_lock + 21
> 4   nanomq                              0x0000000101f4afc5 nni_mtx_lock + 21
> 5   nanomq                              0x0000000101f496e7 nni_task_dispatch + 71
> 6   nanomq                              0x0000000101f37a0b nni_aio_begin + 331
> 7   nanomq                              0x0000000101f69521 tcptran_pipe_recv + 33
> 8   nanomq                              0x0000000101f41519 nni_pipe_recv + 41
> 9   nanomq                              0x0000000101f587c5 nano_ctx_recv + 869
> 10  nanomq                              0x0000000101f44c16 nni_ctx_recv + 54
> 11  nanomq                              0x0000000101f33386 nng_ctx_recv + 310
> 12  nanomq                              0x0000000101f30ad3 server_cb + 8899
> 13  nanomq                              0x0000000101f493f0 nni_taskq_thread + 144
> 14  nanomq                              0x0000000101f4b2ff nni_thr_wrap + 191
> 15  nanomq                              0x0000000101f561f8 nni_plat_thr_main + 120
> 16  libsystem_pthread.dylib             0x00007fff203398fc _pthread_start + 224
> 17  libsystem_pthread.dylib             0x00007fff20335443 thread_start + 15
> zsh: abort      ./build/nanomq/nanomq broker start -tq_thread 8 -max_tq_thread 8 -parallel 1
> ```

somehow, you help me identifying another hidden bug. thank you

**Comment by Grabber** [comment]
@JaylinYu

I think we must review why with a single worker things are going seg. faulting, it may be a signal of other errors we aren't seeing. Which bug have you identified?

**Comment by JaylinYu** [comment]
> @JaylinYu
> 
> I think we must review why it's seg. faulting with single context, it may be a signal of other errors we aren't seeing right now. Which bug have you identified?

this seg fault has been fixed in this pr of nng :https://github.com/nanomsg/nng/commit/d62111974d72ec41d3b736d7e7767e9e8e7bae88
which I have also merged with nanomq.
Please check the the latest commit of master branch. thanks.

The another bug is similar to #174 , just with different trigger condition. We gonna fix this very soon.

**Comment by jld-adriano** [comment]
Does this look like the same error or should I open a new issue?
I'm running in bridge mode, and this happens after a few seconds of transmission, consistently.
Tried running with parallel=2, no difference
```
%This message is indicative of a BUG.
.Report this at https://github.com/emqx/nanomq
"nanomq(nni_panic+0xe4) [0x460a80]
nanomq() [0x46a1e0]
,nanomq(nni_plat_mtx_unlock+0x14) [0x46a390]
'nanomq(nni_mtx_unlock+0x14) [0x466c8c]
nanomq() [0x46c960]
%nanomq(nni_ctx_send+0x3c) [0x463ec4]
%nanomq(nng_ctx_send+0x8c) [0x454b20]
#nanomq(server_cb+0x538) [0x44939c]
&nanomq(nni_task_exec+0x78) [0x466488]
nanomq() [0x459ccc]
,nanomq(nni_aio_finish_sync+0x2c) [0x459d4c]
nanomq() [0x47b8b0]
&nanomq(nni_task_exec+0x78) [0x466488]
nanomq() [0x459ccc]
,nanomq(nni_aio_finish_sync+0x2c) [0x459d4c]
nanomq() [0x4a6a70]
nanomq() [0x46601c]
nanomq() [0x466e28]
nanomq() [0x46a700]
A/lib/aarch64-linux-gnu/libpthread.so.0(+0x77e4) [0xffffb06f07e4]
</lib/aarch64-linux-gnu/libc.so.6(+0xcf59c) [0xffffb05eb59c]```

**Comment by JaylinYu** [comment]
nope this is another bug, check https://github.com/emqx/nanomq/issues/559.
We gonna leave the logging system enhancement behind as last priority

**Comment by JaylinYu** [comment]
> nope this is another bug, check #559.
> We gonna leave the logging system enhancement behind as last priority

**Comment by JaylinYu** [comment]
> Does this look like the same error or should I open a new issue? I'm running in bridge mode, and this happens after a few seconds of transmission, consistently. Tried running with parallel=2, no difference
> 
> ```
> %This message is indicative of a BUG.
> .Report this at https://github.com/emqx/nanomq
> "nanomq(nni_panic+0xe4) [0x460a80]
> nanomq() [0x46a1e0]
> ,nanomq(nni_plat_mtx_unlock+0x14) [0x46a390]
> 'nanomq(nni_mtx_unlock+0x14) [0x466c8c]
> nanomq() [0x46c960]
> %nanomq(nni_ctx_send+0x3c) [0x463ec4]
> %nanomq(nng_ctx_send+0x8c) [0x454b20]
> #nanomq(server_cb+0x538) [0x44939c]
> &nanomq(nni_task_exec+0x78) [0x466488]
> nanomq() [0x459ccc]
> ,nanomq(nni_aio_finish_sync+0x2c) [0x459d4c]
> nanomq() [0x47b8b0]
> &nanomq(nni_task_exec+0x78) [0x466488]
> nanomq() [0x459ccc]
> ,nanomq(nni_aio_finish_sync+0x2c) [0x459d4c]
> nanomq() [0x4a6a70]
> nanomq() [0x46601c]
> nanomq() [0x466e28]
> nanomq() [0x46a700]
> A/lib/aarch64-linux-gnu/libpthread.so.0(+0x77e4) [0xffffb06f07e4]
> </lib/aarch64-linux-gnu/libc.so.6(+0xcf59c) [0xffffb05eb59c]```
> ```

nope this is another bug, check https://github.com/emqx/nanomq/issues/559.
We gonna leave the logging system enhancement behind as last priority

**Comment by JaylinYu** [comment]
> Does this look like the same error or should I open a new issue? I'm running in bridge mode, and this happens after a few seconds of transmission, consistently. Tried running with parallel=2, no difference
> 
> ```
> %This message is indicative of a BUG.
> .Report this at https://github.com/emqx/nanomq
> "nanomq(nni_panic+0xe4) [0x460a80]
> nanomq() [0x46a1e0]
> ,nanomq(nni_plat_mtx_unlock+0x14) [0x46a390]
> 'nanomq(nni_mtx_unlock+0x14) [0x466c8c]
> nanomq() [0x46c960]
> %nanomq(nni_ctx_send+0x3c) [0x463ec4]
> %nanomq(nng_ctx_send+0x8c) [0x454b20]
> #nanomq(server_cb+0x538) [0x44939c]
> &nanomq(nni_task_exec+0x78) [0x466488]
> nanomq() [0x459ccc]
> ,nanomq(nni_aio_finish_sync+0x2c) [0x459d4c]
> nanomq() [0x47b8b0]
> &nanomq(nni_task_exec+0x78) [0x466488]
> nanomq() [0x459ccc]
> ,nanomq(nni_aio_finish_sync+0x2c) [0x459d4c]
> nanomq() [0x4a6a70]
> nanomq() [0x46601c]
> nanomq() [0x466e28]
> nanomq() [0x46a700]
> A/lib/aarch64-linux-gnu/libpthread.so.0(+0x77e4) [0xffffb06f07e4]
> </lib/aarch64-linux-gnu/libc.so.6(+0xcf59c) [0xffffb05eb59c]```
> ```

And the issue has been fixed

**Comment by JaylinYu** [comment]
Logging system has been refactored. Bug is fixed
