### ISSUE TITLE
Ninja Build Fails on Windows 10

### ISSUE THREAD

**Issue by rlevano77** [emqx/nanomq#282]
In Windows 10 using 
GCC v11.2.0
Ninja v1.10.2
Cmake 3.22.1

Build steps :
```
git clone https://github.com/nanomq/nanomq.git ; cd nanomq
git submodule update --init --recursive
mkdir build && cd build
cmake -G Ninja ..
ninja
```

Gives error :  
```
../nanomq/nng/include/nng/nng_debug.h:13:10: fatal error: syslog.h: No such file or directory
   13 | #include <syslog.h>
      
compilation terminated.
ninja: build stopped: subcommand failed.
```

**Comment by JaylinYu** [comment]
Hi,  thanks for reporting. NanoMQ requires POSIX compatible system. Syslog belongs to the POSIX standard.
Windows's GCC does not provide such capability. Please compile it with cygwin.
We will make the Syslog requirement optional in the next release.

**Comment by wanghaEMQ** [comment]
Compile with Cygwin-GCC is still not working ...
What's more, when I commented the ```#include <syslog.h>``` more errors happen in building
for example, sys/ioctl.h, sys/wait.h cannot be found...

**Comment by JaylinYu** [comment]
Hi, we have fixed this @rlevano77
