### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by skyformat99** [emqx/nanomq#364]
1) cmake ..
2)make

Consolidate compiler generated dependencies of target nng
[  0%] Building C object nng/CMakeFiles/nng.dir/src/platform/posix/posix_atomic.c.o
/var/nanomq/nanomq/nng/src/platform/posix/posix_atomic.c:379:20: error: unknown type name ‘nni_atomic_atomic’
 nni_atomic_get_ptr(nni_atomic_atomic *v)
                    ^
/var/nanomq/nanomq/nng/src/platform/posix/posix_atomic.c:389:20: error: unknown type name ‘nni_atomic_atomic’
 nni_atomic_set_ptr(nni_atomic_atomic *v, void *p)
                    ^
make[2]: *** [nng/CMakeFiles/nng.dir/src/platform/posix/posix_atomic.c.o] Error 1
make[1]: *** [nng/CMakeFiles/nng.dir/all] Error 2
make: *** [all] Error 2

**Comment by JaylinYu** [comment]
Hi, which version or commit are you compiling based on?

please be noted that master branch is under heave development for now, so you might encounter some issues ^_^.

**Comment by JaylinYu** [comment]
hi please check again.

**Comment by skyformat99** [comment]
1)  git clone  lastest code;
2) mkdir build
3) cmake ..   make

gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)


Consolidate compiler generated dependencies of target nng
**[ 0%] Building C object nng/CMakeFiles/nng.dir/src/platform/posix/posix_atomic.c.o
/var/nanomq/nanomq/nng/src/platform/posix/posix_atomic.c:379:20: error: unknown type name ‘nni_atomic_atomic’
nni_atomic_get_ptr(nni_atomic_atomic *v)
^
/var/nanomq/nanomq/nng/src/platform/posix/posix_atomic.c:389:20: error: unknown type name ‘nni_atomic_atomic’
nni_atomic_set_ptr(nni_atomic_atomic *v, void *p)
^**
make[2]: *** [nng/CMakeFiles/nng.dir/src/platform/posix/posix_atomic.c.o] Error 1
make[1]: *** [nng/CMakeFiles/nng.dir/all] Error 2
make: *** [all] Error 2

**Comment by skyformat99** [comment]
找到原因了， gcc 4.8的原因。你这个里头啊，用了原子操作，这个是 c11支持的；

你能不能修改让gcc 4.8也支持正常编译

很多嵌入式都是gcc 4.8 ，包括 redhat 7.6

**Comment by JaylinYu** [comment]
Hi 正想回复你来着，我查了一下 GCC 4.9就有atomic了。 原子锁对于nng来说是必须的，可以自己引入atomic头文件来绕过问题。其他绕过的方法我再研究一下

**Comment by JaylinYu** [comment]
Unfortunately, I cannot introduce stdatomic.h due to license confiction.
