### ISSUE TITLE
请问nanomq支持访问控制(ACL)吗？

### ISSUE THREAD

**Issue by Just1ceP4rtn3r** [emqx/nanomq#471]
我看到文档中只描述了username/password认证，不知能否进行topic的访问控制？

**Comment by lee-emqx** [comment]
NanoMQ 暂时还不支持 ACL，我们将会在后续的版本中加入 ACL 功能。

**Comment by Just1ceP4rtn3r** [comment]
您好，我观察到配置文件中存在acl_req相关http接口，但是测试后无法正常使用，请问最新版本(0.10.1)支持ACL吗？

**Comment by JaylinYu** [comment]
应该需要再0.13-0.14版本才能支持ACL

**Comment by JaylinYu** [comment]
ACL is already supported
