### ISSUE TITLE
How can I enable HTTP api port?

### ISSUE THREAD

**Issue by xingdavis** [emqx/nanomq#516]
I am using nanomq:0.6.6 image with running a docker container to run as mqtt broker.but I can't access http api port 8081. Could somebody know what's going on?

docker container show followiing
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/11851006/164141400-f7938645-f15e-445e-91d8-4e6846810db7.png">

<img width="450" alt="image" src="https://user-images.githubusercontent.com/11851006/164141568-d2f74128-c65a-4987-8e1f-27a91fcac8ee.png">

**Comment by JaylinYu** [comment]
Hi The HTTP server is disabled by default. You could enable it via modifying configuration file or follow the instructions here:https://github.com/emqx/nanomq#nanomq-environment-variables

don't forget to restart nanomq after you enable HTTP.

**Comment by xingdavis** [comment]
> Hi The HTTP server is disabled by default. You could enable it via modifying configuration file or follow the instructions here:https://github.com/emqx/nanomq#nanomq-environment-variables
> 
> don't forget to restart nanomq after you enable HTTP.
It's work fine,thanks.
