### ISSUE TITLE
Messages are not droped when expiry interval is exceeded.

### ISSUE THREAD

**Issue by lee-emqx** [emqx/nanomq#525]
Run cmd below to set message-expiry interval 
```
$ mosquitto_pub -t topic_test -m message -V 5 -q 1 -D publish message-expiry-interval 3 -r
```
Run cmd after three seconds, you can receive message too.
```
$ mosquitto_sub -t 'topic_test' -q 1 -V 5
message
```

**Comment by JaylinYu** [comment]
For now, msg expiry interval is not working with retain msg. gonna fix in next release
