### ISSUE TITLE
Connection to broker fails when using LWT with control characters

### ISSUE THREAD

**Issue by carl-cimon** [emqx/nanomq#541]
We're testing nanomq for use with our application which uses sparkplug to communicate. We've been having trouble connecting to the broker from our client, and have determined the issue to be caused by trying to connect with a will message that contains control characters.

As an example, the will message `test will` will allow us to connect, but `test \n will` will prevent connection.

From what I can tell, this completely breaks compatibility with the Sparkplug protocol, as the NDEATH message is sent using the LWT, and this NDEATH message is an encoded protobuf, which often/always contains some control character (from my testing there was consistently a `\n` in the encoded message).

I was able to recreate this problem with multiple clients (MQTT.fx and a C++ client using Apache Paho). If we stop using a will message, our clients are able to connect and publish these encoded protobuf messages normally, so I believe the problem lies with how nanomq handles the will message.

Are we doing something wrong with the configuration of our broker that would be causing this issue? From what I can tell there are no settings that relate to this.

Is this a bug, or are we limited with the contents of our will message? If this is intended, could someone provide the rules for the will message?

Let me know if any additional information is needed from my side.

**Comment by JaylinYu** [comment]
Hi @carl-cimon, currently, the will msg must be UTF-8 encoded for NanoMQ. But as I double confirmed with the spec of Sparkplugb & MQTT， this turns out to be our misinterpretation of the protocol. 
 I will fix this by today.

**Comment by JaylinYu** [comment]
Hi @carl-cimon  please have a check on master branch or the LTS version 0.6.6

**Comment by carl-cimon** [comment]
> With 0.6.6, we were still unable to connect when using a LWT message that contained a control character (I only tested with the `\n` newline this time).

Turns out we were using the previous 0.6.6 tag from two weeks ago. Using the updated 0.6.6 tag solves the issue, we are able to connect with the LWT and subscribe to all topics.

I'd still be aware of the subscription issue on the master branch, since that could cause some issues if not addressed in future versions, but for now we will continue to test our application with the 0.6.6 tag. Thanks for getting this resolved so quickly!

**Comment by JaylinYu** [comment]
> Thanks for the quick response! Unfortunately I don't think this solved our issues, at least not entirely.
> 
> With 0.6.6, we were still unable to connect when using a LWT message that contained a control character (I only tested with the `\n` newline this time).
> 
> With the master branch build, we were able to connect with the LWT, however we had difficulty subscribing to some topics. From what I can tell, trying to subscribe to a topic which includes the topic name used in the LWT caused the subscribing client to disconnect. For example, if our LWT message would be sent on topic `spBv1.0/test/NDEATH/a7e9c79c`, then subscribing to that topic or any topics using wildcards that include that topic (like `#`, `spBv1.0/test/+/a7e9c79c`, `spBv1.0/#`, etc.) resulted in the subscribing client losing connection to the broker.
> 
> Since we are not able to subscribe to the topic which the LWT is published to, there is no way to confirm that it is actually being published when the client disconnects (but if nothing can subscribe to it, I guess that doesn't matter).

Hi @carl-cimon , that's strange. In the most updated master branch, I have no trouble subscribing to the topics as you mentioned: "spBv1.0/test/NDEATH/a7e9c79c" or "spBv1.0/test/+/a7e9c79c". Please be aware that MQTT does not allow to publish to topic with wildcard.
 I would like to dig into it furthermore, so a more detailed testing case is desired.

**Comment by JaylinYu** [comment]
After some investigation, I found this is a bug in MQTT.fx, when MQTT.fx receives multiple PUBLISH packet at once, it send 0 size packet which closes the socket. I don't find similar behavior in other client tools such as nanomq sub/pub or MQTTX/Mosquitto. I recommend you to ignore this bug of MQTT.fx.

**Comment by JaylinYu** [comment]
BTW, If you find my advice useful, please star nanomq so that we can keep our hard work on it! 🥇

**Comment by carl-cimon** [comment]
Just tested with 0.7.0 and the issue I was having with the master branch yesterday is no longer present (even on mqtt.fx, if that was indeed the problem).
