### ISSUE TITLE
subscribe system topic $SYS/brokers/+

### ISSUE THREAD

**Issue by kongweiteng** [emqx/nanomq#580]
hello,when i subscribe '$SYS/brokers/disconnected' or  '$SYS/brokers/connected',i got the message '"username":"(null)","ts":3361588438,"reason_code":"0","client_id":"8e4fa98d14f64ddc93e0748cab531c79"}' or '{"username":"(null)", "ts":3361589081,"proto_name":"MQTT","keepalive":60,"return_code":"0","proto_ver":4,"client_id":"8e4fa98d14f64ddc93e0748cab531c79", "clean_start":1}'

But the timestamp ts is not correct.

I want to get the right time.

What should I do?

thank you

**Comment by JaylinYu** [comment]
sure  gonna change to standard timestamp soon
