### ISSUE TITLE
MQTTv5 Properties Bugs

### ISSUE THREAD

**Issue by stefanodaroit** [emqx/nanomq#626]
I have tested nanomq/nanomq/0.6.6 docker image and I have found some issues:

## Subscription Identifier
As noted in the OASIS specification: “it is a Protocol Error for a PUBLISH packet to contain any Subscription Identifier other than those received in SUBSCRIBE packet which caused it to flow. A PUBLISH packet sent from a Client to a Server MUST NOT contain a Subscription Identifier [MQTT-3.3.4-6]”.

If a client tries to send a PUBLISH packet that includes a “Subscription Identifier” the broker does not report a protocol error, it forwards the packet to subscribers including the property. This happens only if the subscribers do not set themselves a “Subscription Identifier“ for the subscription.

## Including Duplicate Properties
As noted in the OASIS specification, to include a property value more than once is a protocol error for most of the properties (except “User Properties” and “Subscription Identifier”). NanoMQ broker ignores the malformed packet and considers the last value set. This behavior could cause ambiguity..

Test:
A client connects to broker using a crafted CONNECT packet that includes “Maximum Packet Size” twice (the first value is set to 2100, the second to 1024); then it subscribes to “topic/test”  
A second client publish a message of little more than 2048 Byte and then a second one of  little more than 1024 Byte
The first message is discarded by the broker, the second one is received by the first client: so the broker considers the last value set.
Other tests were made including “Session Expiry Interval” and  “Response Topic” twice in respectively a CONNECT and a PUBLISH packet sent by a client. In both tests only the second value is considered by the broker. In the second test property is published twice.

## NoLocal Flag
As noted in the OASIS specification: “it is a Protocol Error to set the No Local bit to 1 on a Shared Subscription [MQTT-3.8.3-4]”. 
NanoMQ broker ignores the specification and lets clients set No Local bit to 1 on Shared Subscription.

## Unsubscription
When a client tries to unsubscribe from a topic the broker often crashes.

**Comment by JaylinYu** [comment]
Hi, thank you for helping us to identify the issues.  I assume "EMQx broker" means NanoMQ here. Will issue a fix this week.


Subscription Identifier
This is a known issue. the 0.6.6ver of NanoMQ does not support all sets of MQTT V5 features, sub ID is one of them. Will tweak the CONNACK packet to mark Subscription Identifier as unavailable. And this has been fixed in most update ver 
 of NanoMQ, the Subscription Identifier of PUBLISH packet will be ignored。

**Comment by stefanodaroit** [comment]
> Hi, thank you for helping us to identify the issues. I assume "EMQx broker" means NanoMQ here. Will issue a fix this week.

Yes, of course. Sorry for the mistake.

> Subscription Identifier
This is a known issue. the 0.6.6ver of NanoMQ does not support all sets of MQTT V5 features, sub ID is one of them. Will tweak the CONNACK packet to mark Subscription Identifier as unavailable. And this has been fixed in most update ver
of NanoMQ, the Subscription Identifier of PUBLISH packet will be ignored

I didn't know it. Well done.

**Comment by JaylinYu** [comment]
@stefanodaroit  Hi bro, we have fixed rhese bugs and merged into the master branch now. Please submit another issue if you find any more issues.

**Comment by JaylinYu** [comment]
gonna close this due to inactivity. All bugs have been fixed
