### ISSUE TITLE
NanoMQ config files

### ISSUE THREAD

**Issue by AmirOsman2020** [emqx/nanomq#656]
I installed nanomq-0.8.0-linux-amd64.deb and it's working fine but I couldn't find the config files in the etc folder on my Linux server

**Comment by JaylinYu** [comment]
Hi Amir, Currently NanoMQ does not install configuration files by default, you need to copy your own config files to /etc folder or set a self-defined path for config file: --conf

**Comment by JaylinYu** [comment]
config file examples could be found here: https://github.com/emqx/nanomq/tree/master/etc
we will copy config file to etc in 0.9.0

**Comment by AmirOsman2020** [comment]
This is great.
