### ISSUE TITLE
memleak in sub property

### ISSUE THREAD

**Issue by JaylinYu** [emqx/nanomq#713]
==1328171==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 256 byte(s) in 4 object(s) allocated from:
    #0 0x7f63fcda7a37 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x562042179025 in nni_zalloc ../nng/src/platform/posix/posix_alloc.c:26
    #2 0x562042149d1c in nng_zalloc ../nng/src/nng.c:66
    #3 0x5620421c7f02 in property_alloc ../nng/src/supplemental/mqtt/mqtt_codec.c:2001
    #4 0x5620421c9d50 in decode_buf_properties ../nng/src/supplemental/mqtt/mqtt_codec.c:2424
    #5 0x5620421ca038 in decode_properties ../nng/src/supplemental/mqtt/mqtt_codec.c:2447
    #6 0x56204211b7d9 in decode_sub_msg ../nanomq/sub_handler.c:49
    #7 0x562042132458 in server_cb ../nanomq/apps/broker.c:263
    #8 0x5620421740ee in nni_task_exec ../nng/src/core/taskq.c:144
    #9 0x5620421586b1 in nni_aio_finish_impl ../nng/src/core/aio.c:454
    #10 0x562042158733 in nni_aio_finish_sync ../nng/src/core/aio.c:469
    #11 0x5620421a1900 in nano_pipe_recv_cb ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:1149
    #12 0x5620421740ee in nni_task_exec ../nng/src/core/taskq.c:144
    #13 0x5620421586b1 in nni_aio_finish_impl ../nng/src/core/aio.c:454
    #14 0x562042158733 in nni_aio_finish_sync ../nng/src/core/aio.c:469
    #15 0x56204220a822 in tcptran_pipe_recv_cb ../nng/src/sp/transport/mqtt/broker_tcp.c:777
    #16 0x5620421738f9 in nni_taskq_thread ../nng/src/core/taskq.c:50
    #17 0x562042174bdb in nni_thr_wrap ../nng/src/core/thread.c:94
    #18 0x56204217d5ac in nni_plat_thr_main ../nng/src/platform/posix/posix_thread.c:266
    #19 0x7f63fcb3b946 in start_thread nptl/pthread_create.c:435

Direct leak of 32 byte(s) in 4 object(s) allocated from:
    #0 0x7f63fcda7867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x562042178ff4 in nni_alloc ../nng/src/platform/posix/posix_alloc.c:20
    #2 0x562042149cfe in nng_alloc ../nng/src/nng.c:60
    #3 0x5620421bc631 in nng_atomic_alloc64 ../nng/src/supplemental/util/platform.c:219
    #4 0x56204211cac6 in sub_ctx_handle ../nanomq/sub_handler.c:252
    #5 0x562042132476 in server_cb ../nanomq/apps/broker.c:264
    #6 0x5620421740ee in nni_task_exec ../nng/src/core/taskq.c:144
    #7 0x5620421586b1 in nni_aio_finish_impl ../nng/src/core/aio.c:454
    #8 0x562042158733 in nni_aio_finish_sync ../nng/src/core/aio.c:469
    #9 0x5620421a1900 in nano_pipe_recv_cb ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:1149
    #10 0x5620421740ee in nni_task_exec ../nng/src/core/taskq.c:144
    #11 0x5620421586b1 in nni_aio_finish_impl ../nng/src/core/aio.c:454
    #12 0x562042158733 in nni_aio_finish_sync ../nng/src/core/aio.c:469
    #13 0x56204220a822 in tcptran_pipe_recv_cb ../nng/src/sp/transport/mqtt/broker_tcp.c:777
    #14 0x5620421738f9 in nni_taskq_thread ../nng/src/core/taskq.c:50
    #15 0x562042174bdb in nni_thr_wrap ../nng/src/core/thread.c:94
    #16 0x56204217d5ac in nni_plat_thr_main ../nng/src/platform/posix/posix_thread.c:266
    #17 0x7f63fcb3b946 in start_thread nptl/pthread_create.c:435

Indirect leak of 256 byte(s) in 4 object(s) allocated from:
    #0 0x7f63fcda7a37 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x562042179025 in nni_zalloc ../nng/src/platform/posix/posix_alloc.c:26
    #2 0x562042149d1c in nng_zalloc ../nng/src/nng.c:66
    #3 0x5620421c7f02 in property_alloc ../nng/src/supplemental/mqtt/mqtt_codec.c:2001
    #4 0x5620421c88d8 in property_parse ../nng/src/supplemental/mqtt/mqtt_codec.c:2157
    #5 0x5620421c9e16 in decode_buf_properties ../nng/src/supplemental/mqtt/mqtt_codec.c:2431
    #6 0x5620421ca038 in decode_properties ../nng/src/supplemental/mqtt/mqtt_codec.c:2447
    #7 0x56204211b7d9 in decode_sub_msg ../nanomq/sub_handler.c:49
    #8 0x562042132458 in server_cb ../nanomq/apps/broker.c:263
    #9 0x5620421740ee in nni_task_exec ../nng/src/core/taskq.c:144
    #10 0x5620421586b1 in nni_aio_finish_impl ../nng/src/core/aio.c:454
    #11 0x562042158733 in nni_aio_finish_sync ../nng/src/core/aio.c:469
    #12 0x5620421a1900 in nano_pipe_recv_cb ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:1149
    #13 0x5620421740ee in nni_task_exec ../nng/src/core/taskq.c:144
    #14 0x5620421586b1 in nni_aio_finish_impl ../nng/src/core/aio.c:454
    #15 0x562042158733 in nni_aio_finish_sync ../nng/src/core/aio.c:469
    #16 0x56204220a822 in tcptran_pipe_recv_cb ../nng/src/sp/transport/mqtt/broker_tcp.c:777
    #17 0x5620421738f9 in nni_taskq_thread ../nng/src/core/taskq.c:50
    #18 0x562042174bdb in nni_thr_wrap ../nng/src/core/thread.c:94
    #19 0x56204217d5ac in nni_plat_thr_main ../nng/src/platform/posix/posix_thread.c:266
    #20 0x7f63fcb3b946 in start_thread nptl/pthread_create.c:435

SUMMARY: AddressSanitizer: 544 byte(s) leaked in 12 allocation(s).

**Comment by wanghaEMQ** [comment]
Which has been fixed in the incoming PR #705
