### ISSUE TITLE
规则引擎的问题

### ISSUE THREAD

**Issue by darcyg** [emqx/nanomq#728]
规则引擎什么时候支持更多action？

现在只有webhook. 似乎没有 republish
webhook的规则也很简单

希望能支持
republish,和shell/bash(就是本地命令行)

**Comment by JaylinYu** [comment]
是想要通过规则引擎还是webhook Republish ？

**Comment by JaylinYu** [comment]
shell/bash是想远程发消息 本地bash?

**Comment by darcyg** [comment]
最好通过规则引擎 内部 转发mqtt消息
通过webhook再republish，是不是效率低一点

shell/bash是想，通过规则触发本地的shell动作，比如调用python脚本，类似webhook。
只是比webhook调用shell减少资源消耗

最好是提供直接的python脚本的action，降低资源消耗。

**Comment by JaylinYu** [comment]
shell/bash 已经能够支持 但是因为安全问题没有开放而已。可以下个版本给出。
规则引擎 repub也在0.10的计划里，webhook应该不会做repub

**Comment by darcyg** [comment]
好的.期待..
正在研究ekuiper。
nanomq和ekuiper之间的关系如何，没搞清楚
nanomq什么时候能出1.0或者推荐在生产环境中用？

**Comment by JaylinYu** [comment]
nanomq 可以作为mqtt消息 source或者sink和kuiper集成。
下一个0.10是实际的1.0 stable release版本

**Comment by JaylinYu** [comment]
Hi republish已经支持，Shell因为安全问题被项目否决了，可以用源码里的 cmd.c自己实现

**Comment by darcyg** [comment]
好的，试一下
