### ISSUE TITLE
Publishing messages from the HTTP API

### ISSUE THREAD

**Issue by AmirOsman2020** [emqx/nanomq#738]
I've been using Nanomq for a while, it's one of the best mqtt brokers I've used however the lack of publishing messages from the HTTP api is really frustrating.
I need to publish mqtt messages from my backend to the client after a specific job is done and this requires publishing messages from the HTTP API, Currently am using the open source version of emqx, it allows publishing messages from the HTTP API, I would love to have this feature in NanoMQ, since its fully open source, unlike emqx some features require the enterprise version.

**Comment by JaylinYu** [comment]
Hi Osman, This is already implemented and merged into master branch, detailed Docs will be released with ver 0.10

**Comment by AmirOsman2020** [comment]
> Hi Osman, This is already implemented and merged into master branch, detailed Docs will be released with ver 0.10

This is great
