### ISSUE TITLE
Store sessions, subscriptions, topics and persisting messages in CassandraDB, ScyllaDB, MongoDB and MySQL

### ISSUE THREAD

**Issue by AmirOsman2020** [emqx/nanomq#739]
Storing sessions, subscriptions and persisting messages to one of these databases (CassandraDB, ScyllaDB, MongoDB) will make things much easier and better since NoSQL databases are known for their performance and horizontal scalability.
Also it's one of the best features in emqx enterprise, we would love to have such a feature in NanoMQ.

**Comment by JaylinYu** [comment]
MySQL is in my own mind... but not decided yet. Will keep you on update!

**Comment by JaylinYu** [comment]
BTW , plz vote here, https://github.com/emqx/nanomq/discussions/540, your suggestion matters a lot!

**Comment by JaylinYu** [comment]
@AmirOsman2020  Hi MySQL is supported as well. you can have a try with rule engine in 0.13

**Comment by AmirOsman2020** [comment]
> @AmirOsman2020  Hi MySQL is supported as well. you can have a try with rule engine in 0.13

This is amazing, I'll give it a shot.
