### ISSUE TITLE
How to configure NANOMQ_WEBSOCKET_URL properly?

### ISSUE THREAD

**Issue by anselanza** [emqx/nanomq#755]
**Is your feature request related to a problem? Please describe.**
The environment variable NANOMQ_WEBSOCKET_URL is listed in the README, but it is quite unclear how to actually use it.

**Describe the solution you'd like**
I'd like to be able to specify the "path" part of the URL only, e.g. `/ws` instead of the default `/mqtt` without also having to specify the protocol, host and port for both WS and WSS which I do not intend to change anyway, or should be set elsewhere.

**Additional context**
The README lists the "value" (?) for NANOMQ_WEBSOCKET_URL as:

> 'nmq-ws://host:port/path', 'nmq-wss://host:port/path'

It's not entirely clear what this means. Do you need to specify a single string (assuming you're using either WS or WSS, not both)? Do you have to specify the protocol, host and port, as well as the path? Or can you simply set the path part and allow the rest to be configured normally?

**Comment by JaylinYu** [comment]
Hi, unfortunately, it doesn't support setting "part" of the path only, no matter if you are using a config file or the environment variable (only for Docker). Although it is not hard to implement such a feature, I suggest replacing the whole URL string with what you want: like set from 'nmq-ws://0.0.0.0/mqtt' to 'nmq-ws://127.0.0.1/newpath'. Apologize that I thought URL thing is a common primitive for everyone. Will explain here:

**nmq-ws:** this string represents the transport implementation, we use it to differ the classical websocket transport from NNG, which is not compatible with MQTT. For example: If you using traditional TCP as transport, then it is 'nmq-tcp',  I am trying to let NNG accept my PR which might unite these different transport categories.

**host:** The IP address of your server or edge gateway, recommend being set as 0.0.0.0 in most cases.

**port:** the port number you want NanoMQ to listen to and process MQTT over WebSocket packets on.             

**path:** The HTTP path for your WebSocket client to send packets. This is totally self-defined.

I usually use: nmq-ws://0.0.0.0:8083/mqtt.

BTW, The WebSocket module of NanoMQ can only deal with MQTT over WebSocket. And the TLS support of WebSocket is not fully finished yet.

**Comment by anselanza** [comment]
Thank you for responding!

I will try using the full URL as you suggest, e.g. in my case it would be `nmq-ws://0.0.0.0:8083/ws`. Presumably when running in Docker this will simply work normally since `0.0.0.0` will correspond to "all interfaces" anyway.

**Comment by JaylinYu** [comment]
BTW I just fixed a bug of websocket in 0.9.2 plz use the most updated ver

**Comment by JaylinYu** [comment]
Thx for reminding me! I didn even notice this, this is a bug
