### ISSUE TITLE
Node is null in LoadConfiguration when executing ```nanomq_cli quic sub ```

### ISSUE THREAD

**Issue by wanghaEMQ** [emqx/nanomq#862]
**Describe the bug**
Node is null when executing ```nanomq_cli quic sub ```

**Expected behavior**
No error happened when using nanomq_cli

**Actual Behavior**
Segment fault happened

**To Reproduce**
.

** Environment Details **
 - NanoMQ version - lastest
 - Operating system and version - osx
 - Compiler and language used - gcc
 - testing scenario .

**Client SDK**
.

**Additional context**
.

**Comment by JaylinYu** [comment]
@wanghaEMQ  is this still valid?

**Comment by wanghaEMQ** [comment]
Nope. I will close this issue.
